package io.minispring.aop.proxy;

/**
 * Implemented by every generated subclass proxy. The two methods are the only bridge between
 * generated bytecode and ordinary Java code; their odd names keep them out of the way of
 * anything a user class might declare.
 */
public interface GeneratedProxy {

    /** Installs the dispatcher. Until this is called every method behaves exactly like the superclass. */
    void miniSpring$activate(ProxyDispatcher dispatcher);

    /**
     * Calls the superclass implementation of the {@code methodIndex}-th proxied method with
     * {@code invokespecial}, i.e. without going through the override again and without reflection.
     */
    Object miniSpring$invokeSuper(int methodIndex, Object[] arguments) throws Throwable;
}
